### ISSUE TITLE
Plugin throws JGit MissingObjectException if executed in a shallow Git clone

### ISSUE THREAD

**Issue by myniva** [dvaske/git-build-info#1]
On our CI server (Jenkins), we do not clone the whole git repo but create a shallow clone of it to only transfer the files needed (something like: `git clone --depth 1 git@github.com:dvaske/git-build-info.git`)

If you execute `git describe` in a scenario like this, you get an exception: `fatal: No names found, cannot describe anything.`. This makes sense since the whole history of the repository is not available.

Unfortunately, executing the git-build-info plugin fails as well. It throws a MissingObjectException:

```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'org.dvaske.gradle.git-build-info']
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:155)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$5.run(DefaultPluginRequestApplicator.java:174)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:212)
	... 61 more
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Missing commit 4d8e763f2537d7b1ab0e7204bd16ac13d1537f79
	at org.eclipse.jgit.api.DescribeCommand.call(DescribeCommand.java:315)
	at org.eclipse.jgit.api.DescribeCommand.call(DescribeCommand.java:76)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.dvaske.gradle.GitBuildInfo.apply(GitBuildInfoPlugin.groovy:98)
	at org.dvaske.gradle.GitBuildInfo.apply(GitBuildInfoPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:139)
	... 64 more
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit 4d8e763f2537d7b1ab0e7204bd16ac13d1537f79
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:147)
	at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:903)
	at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:150)
	at org.eclipse.jgit.revwalk.PendingGenerator.next(PendingGenerator.java:147)
	at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:184)
	at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:435)
	at org.eclipse.jgit.api.DescribeCommand.call(DescribeCommand.java:256)
	... 71 more
```

I was checking the code and wondering whether you might want to enclose https://github.com/dvaske/git-build-info/blob/master/src/main/groovy/org/dvaske/gradle/GitBuildInfoPlugin.groovy#L98 in a try-catch block.

Let me know what you think. I'm happy to test it here and open a pull request if that would be welcome.

**Comment by dvaske** [comment]
Seems like an excellent proposal! If you already have a patch feel free to submit a PR, otherwise I'll try to make some time to look at it next week.

**Comment by myniva** [comment]
pull request #2 opened

**Comment by myniva** [comment]
Thanks for merging! Are you planning to release another version of the plugin which includes the fix soon?

**Comment by dvaske** [comment]
Just did it now 0.6 

-Aske
